### ISSUE TITLE
Unify k8s clients

### ISSUE THREAD

**Issue by bartoszmajsak** [maistra/istio-workspace#150]
##### What can be improved

For installing the operator we use dynamic client introduced by #145. We do have however a typed client for `Session` CRD. This makes the code unnecessarily confusing as we could simply re-use the dynamic client to handle both cases.

##### Why

Less code -> less to maintain and to reason about.

**Comment by aslakknutsen** [comment]
Not a high priority in of it self, but could be a natural part of #35 as that's the 'next time' we need to fiddle with the k8s client on the cli side of things to lookup D/DC

**Comment by aslakknutsen** [comment]
Removed as part of #80
