### ISSUE TITLE
Allow develop command to keep the session when quitting

### ISSUE THREAD

**Issue by bartoszmajsak** [Maistra/istio-workspace#232]
##### What can be improved

When we finish `ike develop` the associated session will be removed, as the TP process is killed and  the operator does clean-up on exit. We would like to have the ability to keep the session alive.

##### Why

We would like to have an ability to keep the session alive (and thus the swapped containers) so that we join later, run tests (external processes) against it or let others go through our new service path.

**Comment by aslakknutsen** [comment]
Is this a thing anymore? Wouldn't this simply be replaced by create/delete?

**Comment by bartoszmajsak** [comment]
> Is this a thing anymore? Wouldn't this simply be replaced by create/delete?

Agree, closing.
