### ISSUE TITLE
Create an image for ike client to run in 

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#236]

**Comment by bartoszmajsak** [comment]
Could you remind me what is the main driver for that? Is it to have CI step based on that? (i.e. when integrating with tekton?)

**Comment by aslakknutsen** [comment]
@bartoszmajsak Correct

**Comment by aslakknutsen** [comment]
See WIP https://github.com/aslakknutsen/istio-workspace-action
