### ISSUE TITLE
Expose a GitHub Action for ‘starting a session’

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#237]

**Comment by bartoszmajsak** [comment]
How is it related to #233? Is it what `ike create` should call on the cluster side?

**Comment by aslakknutsen** [comment]
No, the thinking here is that this is the 'CI-Task' whatever that is that calls 'ike create'

**Comment by aslakknutsen** [comment]
See WIP https://github.com/aslakknutsen/istio-workspace-action
