### ISSUE TITLE
Teleproxy / intercept - how that works in general

### ISSUE THREAD

**Issue by aslakknutsen** [maistra/istio-workspace#323]

**Comment by bartoszmajsak** [comment]
Revise and document findings

**Comment by bartoszmajsak** [comment]
Teleproxy repository seems to be inactive for almost half a year right now. Last PR merged in early October 2019, last push to master the same day.

Later, the whole repository have been merged with the main [ambassador](https://github.com/datawire/ambassador/commit/a0a088749336cb64375da53533157270c8ee6320) repository, so all the commands listed in [old README]() are now separated [cmds](https://github.com/datawire/ambassador/tree/master/cmd) in ambassador main repo.

**Comment by bartoszmajsak** [comment]
Similar to `istio-workspace` they have a feature called [Service Preview](https://www.getambassador.io/docs/latest/topics/using/edgectl/#service-preview-and-edge-control) which works as follows:

- there's `telepresence-proxy` service which works as traffic manager and will route requests to "interceptable deployments"
- interceptable deployment has ambassador agent deployed as a sidecar container (traffic agent) - could be routing to the actual instance running in the pod or tp local process

To define what to intercept `egdectl` command is used. It can define intercept to a service as well as headers, e.g.

`$ edgectl intercept add hello -n namespace -m x-dev=$USER -t localhost:9000`

will add intercept rule to "interceptable service" called `hello`, which, based on `x-dev` header can rout to a process running locally on `localhost:9000`

Note: it seems there's no telepresence on the client side involved.

See the demo video for more context https://youtu.be/LDiyKOa1V_A

**Comment by bartoszmajsak** [comment]
`edgectl connect` sets up connectivity from your laptop to the cluster, so e.g. you can `curl hello` like you would be inside the cluster.

**Comment by bartoszmajsak** [comment]
For more details about `edgectl` see docs https://www.getambassador.io/docs/latest/topics/using/edgectl/edge-control/

**Comment by bartoszmajsak** [comment]
Longer webinar: https://www.youtube.com/watch?v=QfdteN6FePY

**Comment by aslakknutsen** [comment]
Add ServicePreview comparison as asciidoc to repo
