### ISSUE TITLE
Auto expose ports based on D/DC port setup

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#35]
The D/DC config found on the server would have some ports defined. The `ike` CLI would reuse this information to auto set the `--port` parameter.

If you have multiple ports exposed - exposed all of them - get free local ports to be mapped to D/DC.

List all the exposed ports as part of the command output.

**Comment by bartoszmajsak** [comment]
Next step: maybe interactive

**Comment by bartoszmajsak** [comment]
Consider a contribution to TP? (why they are not doing that in the first place?)

**Comment by aslakknutsen** [comment]
@bartoszmajsak I'm checking with TP if there is a reason why they don't support it atm.

**Comment by aslakknutsen** [comment]
Seems pretty easy to implement on the TP side.

**Comment by aslakknutsen** [comment]
https://github.com/aslakknutsen/telepresence/commit/70fa46eece4092c7e539c72f796649f821353c0e

**Comment by aslakknutsen** [comment]
Related upstream fix https://github.com/telepresenceio/telepresence/issues/1356
