### ISSUE TITLE
Watch exclusions - defaults

### ISSUE THREAD

**Issue by bartoszmajsak** [Maistra/istio-workspace#36]
Ignore common project files which should not be watched:

- scm folders
- IDE files
- logs

**Comment by bartoszmajsak** [comment]
For now, I would suggest adding `.git` folder only. Other things are usually defined in `.gitignore` file. WDYT @aslakknutsen?

**Comment by aslakknutsen** [comment]
@bartoszmajsak .git and tp.log maybe? since tp.log is ours?

**Comment by bartoszmajsak** [comment]
Right now it's all `*.log` so I will add `.git/`
