### ISSUE TITLE
How to use self-signed for jwksUri and issuer in a Policy

### ISSUE THREAD

**Issue by olaf-meyer** [Maistra/istio-workspace#413]
##### Issue Overview

I'm sorry, but I'm not sure whether this is the correct place to open this issue. However, I'm running an OpenShift cluster with a self-signed certificate. My application is using a Keycloak server running on this OpenShift cluster for authentication. If I create a Policy that points to this Keycloak server in the attributes `jwksUri` and `issuer`, I get the following error in the Istio-pilot pod (in the discovery container):

```bash 
2020-02-17T12:57:34.675759Z	error	model	Failed to fetch public key from "https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs": Get https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs: x509: certificate signed by unknown authority
2020-02-17T12:57:34.675778Z	warn	Failed to fetch jwt public key from "https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs"
```
If I mount a secret with my signer CA public certificate (with the file name `cert.pem`)  in the path `/etc/pki/tls/` of the Istio pilot, then my application is running.

##### Current Behaviour

Is overwriting the file `/etc/pki/tls/cert.pem` in the Istio pilot container the correct way to add a self-signed certificate to the Istio pilot. How can I ensure that this certificate is still used after an version update of Pilot image by the Istio Operator? Would it make sense to have an attribute in the resource ServiceMeshControlPlane for this purpose?

**Comment by bartoszmajsak** [comment]
Issue moved to [Maistra/istio #99](https://github.com/Maistra/istio/issues/99) via [**ZenHub**](https://www.zenhub.com/)

**Comment by olaf-meyer** [comment]
Thank you very much. I got the information that I needed.
