### ISSUE TITLE
Find cloud native app for demo/development

### ISSUE THREAD

**Issue by bartoszmajsak** [maistra/istio-workspace#441]
##### What can be improved

Cloud-native demo/dev/test app to drive and highlight features of istio-workspace. We should consider the whole full DevOps lifecycle.

##### Why

Showing usefulness on the real-world(ish) app can help people understand where to do our tool fits and how it helps, but also can let us build and test new features thoroughly.

**Comment by aslakknutsen** [comment]
Replaced by #330
