### ISSUE TITLE
Decide on gochecknoglobals

### ISSUE THREAD

**Issue by bartoszmajsak** [maistra/istio-workspace#479]
##### What can be improved

We decided to disable [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals) which checks if there are no globals in the codebase. Lets revise it and decide on its usefulness.

**Comment by bartoszmajsak** [comment]
I think we can't have a global rule for all the cases (even though the linter itself has few exceptions, e.g. `Err...`). We have some globals in the API / Controller code around registering `Scheme` as well as in the test code. I think having this linter disabled is fine. But we should of course have to pay attention in PRs :)

WDYT @aslakknutsen?

**Comment by aslakknutsen** [comment]
I agree globals are generally bad, but we're an 'App' not a 'Lib' so less of a problem. Disabled is fine.
