### ISSUE TITLE
Telepresence can't find pods with long version string

### ISSUE THREAD

**Issue by Humpheh** [maistra/istio-workspace#683]
##### Issue Overview

When running the `ike develop` command it consistently fails with the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 49, in main
    start_proxy = proxy.setup(runner, args)
  File "/usr/local/bin/telepresence/telepresence/proxy/proxy.py", line 157, in setup
    operation.prepare(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 282, in prepare
    pod = get_pod_for_deployment(runner, deployment)  # type: Manifest
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 266, in get_pod_for_deployment
    raise RuntimeError(
RuntimeError: Telepresence pod not found for Deployment 'tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176ed-humphrey'.
```

The telepresence logs repeatedly complain about not being able to find the pods even though they spin up correctly:
```
 120.3 TEL | [98] captured in 0.29 secs.
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176hvxtd
 120.3 TEL | --> Name does not match
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176pv645
 120.3 TEL | --> Name does not match
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176ttkh7
 120.3 TEL | --> Name does not match
 120.3 TEL | END SPAN remote.py:229(get_pod_for_deployment)  119.5s
```

I believe this is due to us using commit SHA for the version meaning that the expected pod name is longer than supported 63 characters so is truncated. As telepresence tries to match the pods that start with the deployment name it is never able to find them.

##### Expected Behaviour

Telepresence to find the pods.

##### Current Behaviour

Telepresence is unable to find the pods due to their name being too long.

##### Steps To Reproduce

I haven't fully tested the theory but it should be possible to reproduce by trying to develop on a deployment with a long version string.

---

I can't tell if this is an issue with this repo or telepresence but I'm happy to go and fix this if you could point me to the place where the deployment name is decided. I imagine that truncating version numbers would be a suitable fix for this?

**Comment by aslakknutsen** [comment]
Hmm, interesting. Could you attach the istio-workspace container log as well? And maybe the Session object on the server for this. 

```
kubectrl get session -o yaml
```

**Comment by aslakknutsen** [comment]
To answer your question;

The new version/name is calculated here https://github.com/maistra/istio-workspace/blob/master/pkg/model/model.go#L142

**Comment by Humpheh** [comment]
Yeah here is the session object - I think this was from a different session I created by has the same issue:

Thanks Aslak - here is the session object. 

`$ kubectl get session -o yaml`
```yaml
apiVersion: v1
items:
- apiVersion: maistra.io/v1alpha1
  kind: Session
  metadata:
    creationTimestamp: "2021-02-10T21:01:46Z"
    finalizers:
    - finalizers.istio.workspace.session
    generation: 1
    name: humphreyshotton-akeun
    namespace: hs-test2
    resourceVersion: "370980450"
    selfLink: /apis/maistra.io/v1alpha1/namespaces/hs-test2/sessions/humphreyshotton-akeun
    uid: aae2eed6-ffb6-47b9-8fc5-9f9bc318aab9
  spec:
    ref:
    - args:
        version: "0.109"
      name: tpserver-deployment
      strategy: telepresence
    route:
      name: hs-ike-test
      type: header
      value: humphrey
  status:
    refs:
    - args:
        version: "0.109"
      name: tpserver-deployment
      resources:
      - action: created
        kind: Deployment
        name: tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176ed-humphreyshotton-akeun
      - action: failed
        kind: Gateway
        name: hs-gateway
      - action: failed
        kind: VirtualService
        name: recallserver-virtualservice-humphreyshotton-akeun
      strategy: telepresence
      targets:
      - action: located
        kind: Deployment
        labels:
          app: tpserver
          application: hsapp
          component: tpserver
          environment: test2
          version: 5678b07dcbecd08b3b6beaf5287302ef51a176ed
        name: tpserver-deployment
      - action: located
        kind: Service
        labels:
          app: tpserver
          application: hsapp
          component: tpserver
          environment: test2
        name: tpserver-service
      - action: located
        kind: Gateway
        labels:
          ike.hosts: '<...>'
        name: hs-gateway
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by aslakknutsen** [comment]
Thank you! 

Probably not related to this specific issue but there seems to be a few `action: failed` attempts to manipulate the VirtualService and Gateway objects there.. for what ever reason. The istio-workspace container log should probably be more helpful to why :)

**Comment by aslakknutsen** [comment]
Also, we currently require the use of DestinationRules to do the version swapping, so if you don't have one that describes the 'current' v we can't manipulate it to add our own new version. And generally stuff won't work. Just a heads up :)

**Comment by Humpheh** [comment]
Yeah I just noticed there were a few errors in the server component so I was going to have a look through them tomorrow! I've been playing around with it so it'a probably my fault. 

That's good to know about the DestinationRules too - thanks!

**Comment by Humpheh** [comment]
I had a go at restricting the length of the version today and it did fix the issue I was having. I tested it by changing the function you mentioned to 
```go
// GetNewVersion returns the new updated version name.
func (r *Ref) GetNewVersion(sessionName string) string {
	version := r.GetVersion()
	if len(version) > 8 {
		version = version[:8]
	}
	return version + "-" + sessionName
}
```
I'm not sure if this is a sensible fix or if it is how many characters would be suitable. What do you think?

**Comment by aslakknutsen** [comment]
@Humpheh Let's roll the magic 8 ball. ;)

It's an ok quick fix, but technically the 'name' of the deployment could be to long regardless of the version length I guess.


longlonglonglongname-v1
longlonglonglongname-v1-session Name would still hit the limit

Maybe a 'NameTrucateValidate' function of some sort here would do? https://github.com/maistra/istio-workspace/blob/master/template/strategies/_basic-version.tpl#L39

**Comment by aslakknutsen** [comment]
The root cause is this faulty assumption in Telepresence: 
https://github.com/telepresenceio/telepresence/blob/master/telepresence/proxy/remote.py#L179

Pod name does not have to begin with "deployment-name" + "-"
