### ISSUE TITLE
Stuck in Leader Election on upgrade

### ISSUE THREAD

**Issue by aslakknutsen** [maistra/istio-workspace#711]
##### Issue Overview

When installing the Operator from Operator Hub and a new version arrives it's impossible to perform the upgrade.

##### Expected Behaviour

The new version is deployed, the old version is deleted and everyone is happy.

##### Current Behaviour

The new version is running and is the elected leader. The new version deploys but never reach Readiness because it's waiting to become leader. Update eventually fail.

##### Steps To Reproduce

1. Install v 0.0.6
2. Update to 0.0.7

**Comment by bartoszmajsak** [comment]
Caused by https://github.com/operator-framework/operator-lib/issues/48

It seems that the solution is to change to the `controller-runtime` approach which is election-by-lease.
