### ISSUE TITLE
Add custom resource view for cli

### ISSUE THREAD

**Issue by aslakknutsen** [maistra/istio-workspace#782]
##### What can be improved

Provide a custom resource view for the kubectl/oc cli's to better expose the state of the Session

##### Why

Easier view of the Session state.

https://medium.com/@xcoulon/customizing-the-server-side-printing-of-your-kubernetes-custom-resources-1c84b7631686

**Comment by bartoszmajsak** [comment]
That's as far as we can get

```
❯ ike develop -d ratings-v1 -p 9080 -r 'ruby details.rb 9080'  --route header:ike-session-id=feature-y
....
❯ oc get sessions
NAME           REF NAME     STRATEGY       ROUTE TYPE   ROUTE NAME       ROUTE VALUE   AGE
bartek-lmwwp   ratings-v1   telepresence   header       ike-session-id   feature-y     54s
```

I was trying to figure out if we e.g. can contact route to have it as one column, but I'm getting an error from kubebuilder saying sth like: 

```
ERRO[0000] Error: Field spec.additionalPrinterColumns[2].JSONPath, Value {@.status.route.type}:{@.status.route.name}={@.status.route.value}: spec.additionalPrinterColumns[2].JSONPath: Invalid value: "{@.status.route.type}:{@.status.route.name}={@.status.route.value}": must be a simple json path starting with . 
```

**Comment by bartoszmajsak** [comment]
Seems that it is not really possible (yet?):

https://github.com/operator-framework/operator-sdk/issues/3872#issuecomment-691745700
