### ISSUE TITLE
Enable wrapcheck when `1.1.0`+  version is released as part of golangci-linter

### ISSUE THREAD

**Issue by bartoszmajsak** [maistra/istio-workspace#791]
##### Issue Overview

As we are using `pkg/errors` to wrap errors in our code, latest release of `golangci-lint` fails on `wrapcheck` linter. `1.39.0` version is using `wrapcheck` `1.0.0`. With `1.1.0` it also supports `pkg/errors` so it won't fail. Once new golangci-lint is available we should enable this linter back (the code has been adjusted so it shouldn't fail).

##### Expected Behaviour

Wrapcheck passes on `errors.Wrap` etc.

##### Current Behaviour

Failing due to older version in `golangci-lint`.

##### Steps To Reproduce

1. Run `golangci-lint run --no-config --disable-all -E wrapcheck --max-same-issues 0 --max-issues-per-linter 0 --sort-results` to see it failing

**Comment by tomarrell** [comment]
Just a heads up, golangci-lint `v1.40.0` has shipped with the latest (v2) version of wrapcheck. You now have full control over the signatures that you want to be ignored.

Hope this helps!

**Comment by bartoszmajsak** [comment]
> Just a heads up, golangci-lint `v1.40.0` has shipped with the latest (v2) version of wrapcheck. You now have full control over the signatures that you want to be ignored.
> 
> Hope this helps!

Cool! Thanks for the heads up and your work! Not sure how you found this dark corner of github but great to hear :)
