### ISSUE TITLE
Telepresence --deployment does not support Openshift DeploymentConfig

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#96]
Resulting in

```
T: Starting network proxy to cluster using the existing proxy Deployment details-v1-test

T: Failed to find deployment details-v1-test:
T: No resources found.
T: Error from server (NotFound): deployments.extensions "details-v1-test" not found

T: Exit cleanup in progress
```

**Comment by aslakknutsen** [comment]
Upstream fix https://github.com/telepresenceio/telepresence/pull/1019

**Comment by bartoszmajsak** [comment]
You might want to create an issue in upstream and add ["news fragment"](https://github.com/telepresenceio/telepresence/pull/930/files#diff-60eec95881c84a3ef3f20130376c00f5) so it will be pulled during release notes assembly

**Comment by aslakknutsen** [comment]
Feature upstream. Missing release. Closing this.
