### ISSUE TITLE
Telepresence 2 compatibility with istio workspace for Openshift

### ISSUE THREAD

**Issue by ilovechai** [maistra/istio-workspace#980]
istio workspace supports Telepresence 1 but Telepresence 1 does not work well with Openshift. Is there any ongoing development to add support for Telepresence 2 with istio workspace?

**Comment by bartoszmajsak** [comment]
Can you shed some more details on why it does not work well with Openshift? I would be very much interested in the following:

- which version of openshift are you using
- what errors are you facing (logs would greatly help us narrowing down the problem)

We test it both with OpenShift and vanilla k8s and we strive to make both supported equally well, so your input will be greatly appreciated.

Thanks!

**Comment by bartoszmajsak** [comment]
We're not planning to add Telepresence v2 at this point - closing the issue.
